[package]
name = "log_pipe"
version = "0.1.0"
edition = "2021"

[dependencies]
ironlog = "0.2.6"      # Replace with the correct version
log = "0.4"
serde_json = "1.0"
clap = { version = "4.3", features = ["derive"] }

